### ISSUE TITLE
Give Upstream Developer Write Access

### ISSUE THREAD

**Issue by BeatLink** [flathub/org.gmusicbrowser.gmusicbrowser#1]
Hey @bilelmoussaoui could you give @squentin write access? They're the upstream developer of gmusicbrowser. I want them to have write access in case something happens to me or my github account

**Comment by BeatLink** [comment]
@bilelmoussaoui any updates on this?

**Comment by bilelmoussaoui** [comment]
An invitation was sent a long time ago
![image](https://user-images.githubusercontent.com/7660997/109428163-081d8480-79f6-11eb-9aa4-53f6895a301b.png)

**Comment by BeatLink** [comment]
Ohh

**Comment by squentin** [comment]
It seems the invite has expired, it says it's valid 7 days. Could you resend it ?

**Comment by BeatLink** [comment]
Mentioning @bilelmoussaoui in case they missed it.
